### ISSUE TITLE
InvalidOperationException: FFmpeg exited with a non-zero exit code (-1073741819)

### ISSUE THREAD

**Issue by hyperpixel34** [Tyrrrz/YoutubeExplode.Converter#37] opened 2021-07-25 17:58 UTC
### Version

The newest

### Details

I tried to download a 8k video, but I get an error from ffmpeg

```InvalidOperationException: FFmpeg exited with a non-zero exit code (-1073741819).
Standard error:
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'E:\Users\<my name>\Eigene Videos\QLED 8K Unrivaled realism in real 8K  Samsung.mp4.stream-1.tmp':
  Metadata:
    encoder         : google/video-file
  Duration: 00:01:38.46, start: -0.007000, bitrate: 128 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[libaom-av1 @ 063177c0] 1.0.0-2379-g861fd02c8
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\Users\<my name>\Eigene Videos\QLED 8K Unrivaled realism in real 8K  Samsung.mp4.stream-2.tmp':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6av01mp41
    creation_time   : 2020-06-04T22:23:24.000000Z
  Duration: 00:01:38.43, start: 0.000000, bitrate: 28787 kb/s
    Stream #1:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 7680x4320, 1098 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
    Metadata:
      creation_time   : 2020-06-04T22:23:24.000000Z
      handler_name    : ISO Media file produced by Google Inc.
[libaom-av1 @ 06e22900] 1.0.0-2379-g861fd02c8
Stream mapping:
  Stream #1:0 -> #0:0 (av1 (libaom-av1) -> h264 (libx264))
  Stream #0:0 -> #0:1 (opus (native) -> aac (native))
```

### Steps to reproduce

Using this line of code:
```await youtube.Videos.DownloadAsync(streamInfos, new ConversionRequestBuilder($"filename{streamInfo.Container}").Build(), progressHandler);```

**Comment by Tyrrrz** [comment] 2021-07-25 20:12
Duplicate of #32.
I'm not sure why that error is happening, but there's already an issue for it.

**Closed by Tyrrrz** 2021-07-25 20:12 UTC
Labels: duplicate
